# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI abc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # builddd:

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18.x, 20.x, 22.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - run: npm ci
  #   - run: npm run build --if-present
  #   - run: npm test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Tests passed!" # Thay bằng lệnh test thực tế

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'pull_request' && needs.test.result == 'success' }}
    steps:
      # Bước 1: In tất cả biến môi trường
      - name: Debug environment variables
        run: |
          echo "=== ALL ENV VARIABLES ==="
          printenv
          docker run -it --rm busybox printenv

      # Bước 2: In các biến cụ thể
      - name: Print specific variables
        run: |
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "TEST_RESULT: ${{ needs.test.result }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
          echo "GITHUB_BASE_REF: ${{ github.base_ref }}"

      # Bước 3: Thực hiện deploy
      - name: Deploy application
        if: ${{ github.event_name == 'pull_request' && needs.test.result == 'success' }}
        run: echo "Deploying to staging..."
